/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package napa;

import javax.swing.ImageIcon;

/**
 *
 * @author Vali
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        logo.setIcon(new ImageIcon("images/logo.png"));
        bg.setIcon(new ImageIcon("images/bg.jpg"));
        captainButton.setIcon(new ImageIcon("images/captain.png"));
        shipButton.setIcon(new ImageIcon("images/ship.png"));
        userButton.setIcon(new ImageIcon("images/user.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        captainButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        shipButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        jPanel1.setLayout(null);

        captainButton.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\NAPA\\images\\captain.png")); // NOI18N
        captainButton.setToolTipText("Captains");
        captainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captainButtonActionPerformed(evt);
            }
        });
        jPanel1.add(captainButton);
        captainButton.setBounds(30, 110, 90, 130);

        userButton.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\NAPA\\images\\user.png")); // NOI18N
        userButton.setToolTipText("Users");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        jPanel1.add(userButton);
        userButton.setBounds(290, 110, 70, 130);

        shipButton.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\NAPA\\images\\ship.png")); // NOI18N
        shipButton.setToolTipText("Ships");
        shipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipButtonActionPerformed(evt);
            }
        });
        jPanel1.add(shipButton);
        shipButton.setBounds(150, 110, 110, 130);

        logo.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\NAPA\\images\\logo.png")); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 0, 90, 100);

        bg.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\NAPA\\images\\bg.jpg")); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void captainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captainButtonActionPerformed
        // TODO add your handling code here:
        CaptainMenu open = new CaptainMenu();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_captainButtonActionPerformed

    private void shipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipButtonActionPerformed
        // TODO add your handling code here:
        ShipMenu menu = new ShipMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shipButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
        UserMenu menu = new UserMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton captainButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton shipButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
