/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package napa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vali
 */
public class ShipDelete extends javax.swing.JFrame {

    boolean ship, user;

    /**
     * Creates new form ShipDelete
     */
    public ShipDelete() {
        initComponents();
        logo.setIcon(new ImageIcon("images/logo.png"));
        bg.setIcon(new ImageIcon("images/bg.jpg"));
        userLabel.setVisible(false);
        userCombo.setVisible(false);
        shipLabel2.setVisible(false);
        shipCombo2.setVisible(false);
        user = false;
        ship = true;

        Statement stmt;
        try {
            Connection con = Methods.DBConector();
            stmt = (Statement) con.createStatement();
            String query = "Select * from ships";
            String query2 = "Select * from users";
            PreparedStatement st = con.prepareStatement(query);
            PreparedStatement st2 = con.prepareStatement(query2);
            ResultSet rs = st.executeQuery();
            ResultSet rs2 = st2.executeQuery();

            while (rs.next()) {
                shipCombo.addItem(rs.getString("name"));
                shipCombo2.addItem(rs.getString("name"));

            }
            while (rs2.next()) {
                userCombo.addItem(rs2.getString("firstName") + " " + rs2.getString("lastName"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        shipLabel = new javax.swing.JLabel();
        selectCombo = new javax.swing.JComboBox<>();
        shipCombo = new javax.swing.JComboBox<>();
        userLabel = new javax.swing.JLabel();
        shipLabel2 = new javax.swing.JLabel();
        userCombo = new javax.swing.JComboBox<>();
        shipCombo2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ship Delete");
        setResizable(false);

        jPanel1.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\NAPA\\images\\logo.png")); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 0, 90, 90);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 130, 50, 17);

        shipLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shipLabel.setForeground(new java.awt.Color(255, 255, 255));
        shipLabel.setText("Ship:");
        jPanel1.add(shipLabel);
        shipLabel.setBounds(20, 170, 35, 17);

        selectCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ship", "User" }));
        selectCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectComboItemStateChanged(evt);
            }
        });
        jPanel1.add(selectCombo);
        selectCombo.setBounds(80, 130, 110, 22);

        jPanel1.add(shipCombo);
        shipCombo.setBounds(80, 170, 110, 22);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("User:");
        jPanel1.add(userLabel);
        userLabel.setBounds(250, 130, 36, 17);

        shipLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shipLabel2.setForeground(new java.awt.Color(255, 255, 255));
        shipLabel2.setText("Ship:");
        jPanel1.add(shipLabel2);
        shipLabel2.setBounds(250, 170, 35, 17);

        jPanel1.add(userCombo);
        userCombo.setBounds(300, 130, 120, 22);

        jPanel1.add(shipCombo2);
        shipCombo2.setBounds(300, 170, 120, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 240, 59, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DELETE SHIP");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 70, 130, 30);

        bg.setIcon(new javax.swing.ImageIcon("D:\\Facultate\\NAPA\\images\\bg.jpg")); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 470, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectComboItemStateChanged
        if (selectCombo.getSelectedItem().toString().equals("User")) {
            userLabel.setVisible(true);
            userCombo.setVisible(true);
            shipLabel2.setVisible(true);
            shipCombo2.setVisible(true);
            shipLabel.setVisible(false);
            shipCombo.setVisible(false);
            user = true;
            ship = false;
        } else {
            userLabel.setVisible(false);
            userCombo.setVisible(false);
            shipLabel2.setVisible(false);
            shipCombo2.setVisible(false);
            shipLabel.setVisible(true);
            shipCombo.setVisible(true);
            user = false;
            ship = true;
        }
    }//GEN-LAST:event_selectComboItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (ship == true) {
            Statement stmt;
            int ids = 0;
            try {
                Connection con = Methods.DBConector();
                stmt = (Statement) con.createStatement();
                String query = "DELETE FROM ships where name=?";
                String query2 = "Select ids from ships where name=?";
                PreparedStatement st = con.prepareStatement(query);
                PreparedStatement st2 = con.prepareStatement(query2);
                st.setString(1, shipCombo.getSelectedItem().toString());
                st2.setString(1, shipCombo.getSelectedItem().toString());
                ResultSet rs = st2.executeQuery();
                while (rs.next()) {
                    ids = Integer.parseInt(rs.getString(1));
                }
                String query3 = "DELETE FROM team where ids=?";
                PreparedStatement st3 = con.prepareStatement(query3);
                st3.setInt(1, ids);

                st.executeUpdate();
                st3.executeUpdate();
                ShipDelete ship = new ShipDelete();
                this.dispose();
                ship.setVisible(true);

                JOptionPane.showMessageDialog(null, "SHIP DELETED!", "Succes", 1);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
            }
        }
        if(user==true){
            Statement stmt;
            int ids = 0,idu =0;
            try {
                Connection con = Methods.DBConector();
                stmt = (Statement) con.createStatement();
                String query = "DELETE FROM team where idu=? and ids=?";
                String query2 = "Select idu from users where firstName=? and lastName=?";
                String query3 = "Select ids from ships where name=?";
                        
                PreparedStatement st = con.prepareStatement(query);
                PreparedStatement st2 = con.prepareStatement(query2);
                PreparedStatement st3 = con.prepareStatement(query3);
                
                String nameSelected = userCombo.getSelectedItem().toString();
                String name[] = nameSelected.split(" ");
                
                st2.setString(1, name[0]);
                st2.setString(2, name[1]);
                st3.setString(1, shipCombo2.getSelectedItem().toString());
                
                ResultSet rs2 = st2.executeQuery();
                ResultSet rs3 = st3.executeQuery();
                
                while(rs2.next()){
                    idu = Integer.parseInt(rs2.getString(1));
                }
                while(rs3.next()){
                    ids = Integer.parseInt(rs3.getString(1));
                }
                st.setInt(1,idu);
                st.setInt(2,ids);
                st.executeUpdate();
                ShipDelete ship = new ShipDelete();
                this.dispose();
                ship.setVisible(true);

                JOptionPane.showMessageDialog(null, "USER TEAM DELETED!", "Succes", 1);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShipDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShipDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShipDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShipDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShipDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> selectCombo;
    private javax.swing.JComboBox<String> shipCombo;
    private javax.swing.JComboBox<String> shipCombo2;
    private javax.swing.JLabel shipLabel;
    private javax.swing.JLabel shipLabel2;
    private javax.swing.JComboBox<String> userCombo;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
